image:
  file: .gitpod/dev.dockerfile

tasks:
  - name: Unit Test Coverage
    init: gp sync-await installation
    command: |
      npm run test:unit
      cd coverage/lcov-report/
      http-server -p 8000 &
      cd ../../
      npx vitest
  - name: Run Documentation Page
    init: |
      cd /workspace/webdriverio/website
      npm install
    command: |
      cd /workspace/webdriverio/website
      npm start
  - name: Setup WebdriverIO Development Environment
    init: |
      npm install --legacy-peer-deps
      npm run setup
      gp sync-done installation
    command: npm run watch
  - name: Welcome Bash
    init: gp sync-await installation
    command: node .gitpod/welcome.mjs

ports:
  - port: 3000
    onOpen: notify
    visibility: public
  - port: 8000
    onOpen: notify
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: prevent-merge-on-error
    addComment: false
    addBadge: true

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - DigitalBrainstem.javascript-ejs-support
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
