verbose: false
instrumentation:
  include-all-sources: true
  extensions:
    - .js
reporting:
  reports:
    - json-summary
    - lcov
  watermarks:
    statements: [50, 80]
    lines: [50, 80]
    functions: [50, 80]
    branches: [50, 80]
