project_id: '576975'
api_token_env: CROWDIN_PERSONAL_TOKEN
languages_mapping:
  two_letters_code:
    pt-BR: pt-BR
preserve_hierarchy: 1
files:
  - source: /website/i18n/en/**/*
    translation: /website/i18n/%two_letters_code%/**/%original_file_name%
    languages_mapping: []
  - source: /website/docs/**/*
    translation: /website/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    languages_mapping: []
  - source: /website/community/**/*
    translation: /website/i18n/%two_letters_code%/docusaurus-plugin-content-docs-community/current/**/%original_file_name%
    languages_mapping: []
  - source: /website/src/pages/**/*
    translation: /website/i18n/%two_letters_code%/docusaurus-plugin-content-pages/**/%original_file_name%
    ignore:
      - /**/*.js
      - /**/*.jsx
      - /**/*.ts
      - /**/*.tsx
      - /**/*.css
    languages_mapping: []
