packages:
  - 'packages/**'
  - 'infra/**'
  - 'website/**'
  - 'e2e/**'
  - 'tests/**'
  - 'tests/typings/**'
  - 'examples/wdio/**'
  - 'examples/standalone/**'
  - 'examples/pageobject/**'
  - 'examples/cloudservices/**'
  - 'examples/bidi/**'
  - 'examples/appium/**'
