packages:
  - packages/**
  - infra/**
  - website/**
  - e2e/**
  - tests/**
  - tests/typings/**
  - examples/wdio/**
  - examples/standalone/**
  - examples/pageobject/**
  - examples/cloudservices/**
  - examples/bidi/**
  - examples/appium/**

onlyBuiltDependencies:
  - sharp

patchedDependencies:
  cddl@0.12.0: patches/cddl@0.12.0.patch
  cddl2ts@0.2.2: patches/cddl2ts@0.2.2.patch
