export { SnapshotError } from './errors.js'
export { RefRegistry, refId, type RefEntry, type RefErrorCode, type RefErrorFactory } from './refs.js'
export type { CollectOptions, CollectResult } from './web.js'
export { collectScript, collectWeb, type CollectHow, type CollectWebResult } from './collect.js'
export { countRefs, formatSnapshot, onlyInteractive, type FormatOptions, type CandidateKind, type SnapshotCandidate, type SnapshotNode, type SnapshotRef } from './format.js'
export { diffLines, unifiedDiff } from './diff.js'
export { attachSelectors } from './selectors.js'
export { nativePlatform, parseNativeSource, scopeNativeTree, type Located, type NativePlatform, type ParsedNative } from './native.js'
export { inViewport } from './viewport.js'
