export { SnapshotError } from './errors.js'
export { REF_PATTERN, RefRegistry, refFunction, refId, type RefEntry, type RefErrorCode, type RefErrorFactory } from './refs.js'
export { collectInPage, type CollectOptions, type CollectResult } from './web.js'
export { collectWeb, type CollectHow, type CollectWebResult } from './collect.js'
export { compactTree, countRefs, formatLine, formatSnapshot, onlyInteractive, type FormatOptions, type SnapshotNode, type SnapshotRef } from './format.js'
export { diffLines, unifiedDiff } from './diff.js'
export { attachSelectors, nativeCandidates, type SelectorNode } from './selectors.js'
export { parseXml, type XmlNode } from './xml.js'
export { nativePlatform, parseNativeSource, scopeNativeTree, type Located, type NativePlatform, type ParsedNative } from './native.js'
export { RECORDER_KEY, pageRecorder } from './recorder.js'
export { MAX_BLOCK_LINES, blockAround, headingAbove, lineTest, matchLines, readableUrl, searchLines, stem } from './find.js'
export { inViewport } from './viewport.js'
