name: 💡 Feature request
description: Suggest an idea for WebdriverIO.
title: "[💡 Feature]: <title>"
labels: [Idea 💡, Needs Triaging ⏳]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for taking the time and for sharing your great idea with us. Like many WebdriverIO is an open source project and lives from these great ideas.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered.
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/webdriverio/webdriverio/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
