export const PROTOCOL_VERSION = 1
export const STATE_VERSION = 1

export const DEFAULT_SESSION = 'default'
export const SESSION_NAME_PATTERN = /^[A-Za-z0-9_-]{1,64}$/
export const REF_PATTERN = /^e\d+$/

export const DEFAULT_ACTION_TIMEOUT = 30_000
export const DEFAULT_EXEC_TIMEOUT = 60_000
export const DEFAULT_LAUNCH_TIMEOUT = 180_000
export const DEFAULT_IDLE_TIMEOUT = '30m'
export const DEFAULT_VIEWPORT = { width: 1280, height: 720 }
export const DEFAULT_SNAPSHOT_MAX_CHARS = 8000
export const MAX_QUEUE_LENGTH = 16
export const EVENT_BUFFER_SIZE = 1000
export const WATCHDOG_INTERVAL = 5_000
export const EXEC_INLINE_LIMIT = 256 * 1024
export const MIN_NODE_VERSION = '22.19.0'

export const EXIT_CODES = {
    OK: 0,
    FAILURE: 1,
    USAGE: 2,
    MISSING_DEPENDENCY: 3,
    SESSION_NOT_FOUND: 4
} as const

export const ERROR_CODES = {
    USAGE: EXIT_CODES.USAGE,
    MISSING_DEPENDENCY: EXIT_CODES.MISSING_DEPENDENCY,
    MISSING_APPIUM_DRIVER: EXIT_CODES.MISSING_DEPENDENCY,
    MISSING_BINARY: EXIT_CODES.MISSING_DEPENDENCY,
    MISSING_CREDENTIALS: EXIT_CODES.MISSING_DEPENDENCY,
    SESSION_NOT_FOUND: EXIT_CODES.SESSION_NOT_FOUND,
    SESSION_EXISTS: EXIT_CODES.FAILURE,
    SESSION_START_FAILED: EXIT_CODES.FAILURE,
    SESSION_DIED: EXIT_CODES.FAILURE,
    BUSY: EXIT_CODES.FAILURE,
    TIMEOUT: EXIT_CODES.FAILURE,
    EXEC_ERROR: EXIT_CODES.FAILURE,
    ELEMENT_NOT_FOUND: EXIT_CODES.FAILURE,
    REF_NOT_FOUND: EXIT_CODES.FAILURE,
    REF_STALE: EXIT_CODES.FAILURE,
    NOT_SUPPORTED: EXIT_CODES.FAILURE,
    BIDI_REQUIRED: EXIT_CODES.FAILURE,
    VISUAL_MISMATCH: EXIT_CODES.FAILURE,
    NO_MATCH: EXIT_CODES.FAILURE,
    CHECK_FAILED: EXIT_CODES.FAILURE,
    INTERNAL: EXIT_CODES.FAILURE
} as const

export type ErrorCode = keyof typeof ERROR_CODES
