declare module 'lighthouse';
declare module 'lighthouse/lighthouse-core/lib/network-recorder';
declare module 'lighthouse/lighthouse-core/config/constants';
declare module 'lighthouse/lighthouse-core/audits/diagnostics'
declare module 'lighthouse/lighthouse-core/audits/mainthread-work-breakdown'
declare module 'lighthouse/lighthouse-core/audits/metrics'
declare module 'lighthouse/lighthouse-core/audits/server-response-time'
declare module 'lighthouse/lighthouse-core/audits/metrics/cumulative-layout-shift'
declare module 'lighthouse/lighthouse-core/audits/metrics/first-contentful-paint'
declare module 'lighthouse/lighthouse-core/audits/metrics/largest-contentful-paint'
declare module 'lighthouse/lighthouse-core/audits/metrics/speed-index'
declare module 'lighthouse/lighthouse-core/audits/metrics/interactive'
declare module 'lighthouse/lighthouse-core/audits/metrics/total-blocking-time'
declare module 'lighthouse/lighthouse-core/scoring'
declare module 'lighthouse/lighthouse-core/config/default-config'
