import acceptAlert from './commands/acceptAlert'
import addCookie from './commands/addCookie'
import back from './commands/back'
import closeWindow from './commands/closeWindow'
import createWindow from './commands/createWindow'
import deleteAllCookies from './commands/deleteAllCookies'
import deleteCookie from './commands/deleteCookie'
import deleteSession from './commands/deleteSession'
import dismissAlert from './commands/dismissAlert'
import elementClear from './commands/elementClear'
import elementClick from './commands/elementClick'
import elementSendKeys from './commands/elementSendKeys'
import executeAsyncScript from './commands/executeAsyncScript'
import executeScript from './commands/executeScript'
import findElement from './commands/findElement'
import findElementFromElement from './commands/findElementFromElement'
import findElements from './commands/findElements'
import findElementsFromElement from './commands/findElementsFromElement'
import forward from './commands/forward'
import getActiveElement from './commands/getActiveElement'
import getAlertText from './commands/getAlertText'
import getAllCookies from './commands/getAllCookies'
import getElementAttribute from './commands/getElementAttribute'
import getElementCSSValue from './commands/getElementCSSValue'
import getElementComputedLabel from './commands/getElementComputedLabel'
import getElementComputedRole from './commands/getElementComputedRole'
import getElementProperty from './commands/getElementProperty'
import getElementRect from './commands/getElementRect'
import getElementTagName from './commands/getElementTagName'
import getElementText from './commands/getElementText'
import getNamedCookie from './commands/getNamedCookie'
import getPageSource from './commands/getPageSource'
import getTimeouts from './commands/getTimeouts'
import getTitle from './commands/getTitle'
import getUrl from './commands/getUrl'
import getWindowHandle from './commands/getWindowHandle'
import getWindowHandles from './commands/getWindowHandles'
import getWindowRect from './commands/getWindowRect'
import isElementEnabled from './commands/isElementEnabled'
import isElementSelected from './commands/isElementSelected'
import navigateTo from './commands/navigateTo'
import newSession from './commands/newSession'
import performActions from './commands/performActions'
import refresh from './commands/refresh'
import releaseActions from './commands/releaseActions'
import sendAlertText from './commands/sendAlertText'
import setTimeouts from './commands/setTimeouts'
import setWindowRect from './commands/setWindowRect'
import status from './commands/status'
import switchToFrame from './commands/switchToFrame'
import switchToParentFrame from './commands/switchToParentFrame'
import switchToWindow from './commands/switchToWindow'
import takeElementScreenshot from './commands/takeElementScreenshot'
import takeScreenshot from './commands/takeScreenshot'

export {
    acceptAlert, addCookie, back, closeWindow, createWindow, deleteAllCookies, deleteCookie, deleteSession,
    dismissAlert, elementClear, elementClick, elementSendKeys, executeAsyncScript, executeScript, findElement,
    findElementFromElement, findElements, findElementsFromElement, forward, getActiveElement, getAlertText,
    getAllCookies, getElementAttribute, getElementCSSValue, getElementComputedLabel, getElementComputedRole,
    getElementProperty, getElementRect, getElementTagName, getElementText, getNamedCookie, getPageSource,
    getTimeouts, getTitle, getUrl, getWindowHandle, getWindowHandles, getWindowRect, isElementEnabled,
    isElementSelected, navigateTo, newSession, performActions, refresh, releaseActions, sendAlertText,
    setTimeouts, setWindowRect, status, switchToFrame, switchToParentFrame, switchToWindow, takeElementScreenshot,
    takeScreenshot
}
