export const TestFrameworkConstants = {
    KEY_TEST_UUID: 'test_uuid',
    KEY_TEST_ID : 'test_id',
    KEY_TEST_NAME : 'test_name',
    KEY_TEST_FILE_PATH : 'test_file_path',
    KEY_TEST_TAGS : 'test_tags',
    KEY_TEST_RESULT : 'test_result',
    KEY_TEST_RESULT_AT : 'test_result_at',
    KEY_TEST_STARTED_AT : 'test_started_at',
    KEY_TEST_ENDED_AT : 'test_ended_at',
    KEY_TEST_LOCATION : 'test_location',
    KEY_TEST_SCOPE : 'test_scope',
    KEY_TEST_SCOPES : 'test_scopes',
    KEY_TEST_FRAMEWORK_NAME : 'test_framework_name',
    KEY_TEST_FRAMEWORK_VERSION : 'test_framework_version',
    KEY_TEST_CODE : 'test_code',
    KEY_TEST_RERUN_NAME : 'test_rerun_name',
    KEY_PLATFORM_INDEX : 'platform_index',
    KEY_TEST_FAILURE : 'test_failure',
    KEY_TEST_FAILURE_TYPE : 'test_failure_type',
    KEY_TEST_FAILURE_REASON : 'test_failure_reason',
    KEY_TEST_LOGS : 'test_logs',
    KEY_TEST_META : 'test_meta',
    KEY_SESSION_NAME : 'test_session_name',
    KEY_AUTOMATE_SESSION_NAME : 'automate_session_name',
    KEY_AUTOMATE_SESSION_STATUS: 'automate_session_status',
    KEY_AUTOMATE_SESSION_REASON: 'automate_session_reason',
    KEY_EVENT_STARTED_AT : 'event_started_at',
    KEY_EVENT_ENDED_AT : 'event_ended_at',
    KEY_HOOK_ID : 'hook_id',
    KEY_HOOK_RESULT : 'hook_result',
    KEY_HOOK_LOGS : 'hook_logs',
    KEY_HOOK_NAME : 'hook_name',
    DEFAULT_TEST_RESULT : 'pending',
    DEFAULT_HOOK_RESULT : 'pending',
    KIND_SCREENSHOT : 'TEST_SCREENSHOT',
    KIND_LOG : 'TEST_LOG',
    HOOK_REGEX : '^(BEFORE_|AFTER_)',
}
