name: Build WebdriverIO

on:
  workflow_call:
  # Make this a reusable workflow, no value needed
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  build:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 🧑‍🔧 Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: 👷 Bootstrap Packages
        run: pnpm run setup
        shell: bash
        env:
          NODE_ENV: production
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬆️ Upload Build Artifacts
        uses: ./.github/workflows/actions/upload-archive
        with:
          name: webdriverio
          output: webdriverio-build.zip
          paths: packages/*/build packages/*/cjs
