name: Continuous Releases

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write
      packages: read
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 🧑‍🔧 Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: 👷 Bootstrap Packages
        run: pnpm run setup
        shell: bash
        env:
          NODE_ENV: production
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: pnpx pkg-pr-new publish --pnpm './packages/*'
