name: Manual NPM Publish

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: "Release Type"
        required: true
        type: choice
        default: "patch"
        options:
          - patch
          - minor
          - major
      distTag:
        description: 'NPM tag (e.g. use "next --canary" to release a test version, add "--force-publish" to release all packages)'
        required: true
        default: 'v8'

env:
  NPM_CONFIG_PROVENANCE: true

jobs:
  authorize:
    name: Authorize Actor
    uses: ./.github/workflows/authorize-publisher.yml
    secrets: inherit
  release:
    permissions:
      contents: write
      id-token: write
    needs: [authorize]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'v8'
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.x
      - name: Upgrade npm for trusted publishing
        run: npm install -g npm@11.5.1
      - name: Git Setup
        run: |
          git config --global user.email "bot@webdriver.io"
          git config --global user.name "WebdriverIO Release Bot"
      - name: Install Dependencies
        run: npm ci
      - name: Release
        run: |
          npm run setup
          npm run generate:typings
          npx lerna publish ${{github.event.inputs.releaseType}} --exact --yes --dist-tag ${{github.event.inputs.distTag}}
          npm run pushReleaseTag
        env:
          NODE_ENV: production
          GITHUB_AUTH: ${{ secrets.GITHUB_TOKEN }}
