name: CJS Interoperability Tests

on:
  workflow_call:
    # Make this a reusable workflow, no value needed
    # https://docs.github.com/en/actions/using-workflows/reusing-workflows

jobs:
  check:
    name: CJS Interoperability Tests
    permissions:
      contents: read
    # Workaround while waiting for 24.04 to be fixed with node 24.16 & puppeteer hanging on unzipping
    runs-on: ubuntu-22.04
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: 🧑‍🔧 Get Core Dependencies
        uses: ./.github/workflows/actions/get-core-dependencies

      - name: Download Build Archive
        uses: ./.github/workflows/actions/download-archive
        with:
          name: webdriverio
          path: .
          filename: webdriverio-build.zip

      - name: CJS Interoperability Tests
        run: pnpm run test:interop
        shell: bash

      - name: Check Git Context
        uses: ./.github/workflows/actions/check-git-context
