name: "Get Core Dependencies"
description: "sets the node version & initializes core dependencies"
runs:
  using: composite
  steps:
    - name: 📦 Setup pnpm
      uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

    - name: 🐢 Setup Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: ".nvmrc"
        cache: "pnpm"

    - name: 🏗️ Install Dependencies
      run: pnpm install
      shell: bash

    - name: 🔧 Git Config
      run: git config --global core.autocrlf false
      shell: bash
